# ---
# defaults:
#   - wandb: defaults
#   - hydra: defaults
#   - cam_embd: defaults
#   - _self_
# general:
#   device: 0
#   random_seed: 0
#   mixed_precision: false
# data:
#   data_path: data/Singleprojections_withmask
#   training_resolution: 128
#   input_images: 1
#   batch_size: 4
#   num_workers: 2
# opt:
#   iterations: 100000
#   base_lr: 0.000002
#   betas: [0.9, 0.999]
#   loss: l2
#   imgs_per_obj: 4
#   accumulation_steps: 2
#   ema:
#     use: true
#     beta: 0.9999
#     update_every: 10
#     update_after_step: 100
#   pretrained_ckpt: null
#   # 损失权重
#   w_l12: 1.0
#   w_ssim: 0.25
#   w_tv: 0.2
#   # 前景/背景权重
#   foreground_weight: 5.0  # 前景区域的权重
#   background_weight: 0.1  # 背景区域的权重
#   warmup_steps: 1000
#   weight_decay: 0.01
# model:
#   max_sh_degree: 1
#   name: SingleUNet
#   scale_bias: 0.02
#   scale_scale: 0.003
#   xyz_scale: 0.1
#   xyz_bias: 0.0
#   z_near: 0.1
#   z_far: 2
#   use_zrange: true
#   depth_scale: 1.0
#   depth_bias: 0.5
#   network_without_offset: false
#   network_with_offset: true
#   attention_resolutions: [16]
#   num_blocks: 4
#   cross_view_attention: true
#   base_dim: 128
#   isotropic: false
#   density_scale: 1.0
#   xyz_range: 0.2
#   density_bias: 1

# logging:
#   wandb_project: "SingleProjReconWithMask"
#   wandb_run_name: "1"
#   disable_wandb: false
#   wandb_offline: false
#   ckpt_iterations: 5000
#   val_log: 1000
#   loss_log: 10
#   render_log: 100
#   volume_save_interval: 10000
---
# defaults:
#   - wandb: defaults
#   - hydra: defaults
#   - cam_embd: defaults
#   - _self_
# general:
#   device: 0
#   random_seed: 0
#   mixed_precision: false
# data:
#   data_path: data/Singleprojections_withmask
#   training_resolution: 128
#   input_images: 1
#   batch_size: 8
#   num_workers: 2
# opt:
#   iterations: 100000
#   base_lr: 0.0001
#   betas: [0.9, 0.999]
#   loss: l1
#   imgs_per_obj: 4
#   accumulation_steps: 2
#   ema:
#     use: true
#     beta: 0.9999
#     update_every: 10
#     update_after_step: 100
#   pretrained_ckpt: null
#   # 损失权重
#   w_l12: 1.0
#   w_ssim: 0.25
#   w_tv: 0.05
#   # 前景/背景权重
#   foreground_weight: 5.0  # 前景区域的权重
#   background_weight: 1  # 背景区域的权重
#   warmup_steps: 1000
#   weight_decay: 0.01
# model:
#   max_sh_degree: 1
#   name: SingleUNet

#   scale_bias: 0.1
#   scale_scale: 0.5

#   xyz_scale: 1
#   xyz_bias: 0.0
#   xyz_range: 0.2

#   depth_scale: 1.0
#   depth_bias: 0

#   density_scale: 0.1
#   density_bias: -0.5

#   z_near: 5
#   z_far: 10
#   use_zrange: true

#   network_without_offset: false
#   network_with_offset: true
#   attention_resolutions: [16]
#   num_blocks: 4
#   cross_view_attention: true
#   base_dim: 128
#   isotropic: false




# logging:
#   wandb_project: "SingleProjReconWithMask"
#   wandb_run_name: "6"
#   disable_wandb: false
#   wandb_offline: false
#   ckpt_iterations: 5000
#   val_log: 100
#   loss_log: 1
#   render_log: 10
#   volume_save_interval: 10000
# ---
# ---
defaults:
  - wandb: defaults
  - hydra: defaults
  - cam_embd: defaults
  - _self_
general:
  device: 0
  seed: 0
  mixed_precision: false

data:
  data_path: data/Sparse_challenge
  training_resolution: 512
  input_images: 1
  batch_size: 5
  num_workers: 0
  input_views: 1
opt:
  iterations: 5000000
  mem_clean_interval: 1000
  min_lr_factor: 0.1
  base_lr: 0.00001
  betas: [0.9, 0.999]
  loss: l1
  use_fixed_lr: true
  imgs_per_obj: 4
  accumulation_steps: 1
  ema:
    use: false
    beta: 0.9999
    update_every: 10
    update_after_step: 100
  pretrained_ckpt: null
  # 损失权重
  w_l12: 1.0
  w_ssim: 0.2
  w_tv: 0
  lambda_xyz_boundary: 0.1

  warmup_steps: 1000
  weight_decay: 0.01
model:
  max_sh_degree: 1
  name: SingleUNet

  scale_bias: 0.03
  scale_scale: 0.1

  xyz_scale: 0.1
  xyz_bias: 0
  xyz_range: 1

  depth_scale: 1.0
  depth_bias: 0

  density_scale: 0.1
  density_bias: -3

  z_near: 6.5
  z_far: 9.5
  use_zrange: true
  network_without_offset: false
  network_with_offset: true
  attention_resolutions: [16]
  num_blocks: 4
  cross_view_attention: true
  base_dim: 128
  isotropic: false
  num_gaussians: 1



logging:
  wandb_project: "general train_Sparse_challenge"
  wandb_run_name: "1"
  disable_wandb: true
  wandb_offline: false
  ckpt_iterations: 500
  val_log: 100
  loss_log: 10
  render_log: 10
  volume_save_interval: 10000
  output_dir: experiments_out
  resume_ckpt: null
  ckpt_every: 100
